name: ci-macos

on:
  push:
    paths:
      - '**'
      - '!COPYING'
      - '!COPYING-asm'
      - '!INSTALL'
      - '!**.md'
      - '!.clang*'
      - '!.gitignore'
      - '!.gitattributes'
      - '!.github/workflows/*'
      - '.github/workflows/ci-macos.yml'
  pull_request:
    paths:
      - '**'
      - '!COPYING'
      - '!COPYING-asm'
      - '!INSTALL'
      - '!**.md'
      - '!.clang*'
      - '!.gitignore'
      - '!.gitattributes'
      - '!.github/workflows/*'
      - '.github/workflows/ci-macos.yml'

jobs:
  ci-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        generator: [make, ninja, xcode]
        include:
          - generator: make
            cmake_generator: "Unix Makefiles"
          - generator: ninja
            cmake_generator: "Ninja"
          - generator: xcode
            cmake_generator: "Xcode"
    steps:
      - name: Install dependencies
        run: |
          brew install boost make ninja
          brew install --with-toolchain llvm
      - name: Checkout code
        uses: actions/checkout@master
      - name: Configure
        run: |
          export LDFLAGS="-L$(brew --prefix boost)/lib -L$(brew --prefix llvm)/lib$LDFLAGS"
          export CFLAGS="-I$(brew --prefix boost)/include -I$(brew --prefix llvm)/include$CFLAGS"
          export CXXFLAGS="-I$(brew --prefix boost)/include -I$(brew --prefix llvm)/include $CXXFLAGS"
          export CC="-I$(brew --prefix llvm)/bin/clang"
          export CXX="-I$(brew --prefix llvm)/bin/clang++"
          cmake -S . -B build -G "${{ matrix.cmake_generator }}"
      - name: Build
        run: |
          cmake --build build -j2
